# Generated by Django 2.2.17 on 2020-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_kjkjj'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='kjhkhjkh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='uiews',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
